apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: autochrome-api
spec:
  interval: 5m
  url: ssh://git@github.com:22/391agency/autochrome-api.git
  secretRef:
    name: autochrome-api-auth
  ref:
    branch: main
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/charts/
