apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: testpi
spec:
  interval: 5m
  url: ssh://git@github.com/stefanprodan/podinfo
  ref:
    branch: main
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/charts/
